---
- name: Install-docker-test
  hosts: docker
  become: true
  roles:
    - geerlingguy.docker
  vars_files:
    - group_vars/secrets.yml
  vars:
    ansible_become_pass: "{{ ansible_become_pass_id }}"
   

