name: tsdproxy
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/tsdproxy/data:/data
      - /opt/appdata/tsdproxy/config:/config
    environment:
      - TSDPROXY_AUTHKEY=${TSDPROXY_AUTHKEY}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - "8080:8080"