ansible_become_pass: "{{ lookup('bitwarden.secrets.lookup', '<bitwarden-secret-UUID>') }}"
komodo_passkey: "{{ lookup('bitwarden.secrets.lookup', '<bitwarden-secret-UUID>') }}"
ansible_sudo_pass_servarr: "{{ lookup('bitwarden.secrets.lookup', '<bitwarden-secret-UUID>') }}"